name: ci

on:
  push:
    branches:
      - 'develop'

env:
  IMAGE_NAME: "tlunaaa/scart-auth"
  CONTAINER_NAME: "orchestation_auth_1"
  SERVICE_NAME: "auth"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tlunaaa/scart-auth:latest
